[package]
name = "my_casbin"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
my_jwt.workspace = true
salvo.workspace = true
salvo-casbin.workspace = true
casbin.workspace = true
